services:
  - name: "test"
    endpoints:
      - url: "{{env(TEST_1_URL)}}?date={{%Y-%m-%d}}&rand={{rand(1,100)}}"
        headers:
          Authorization: "{{env(TEST_1_AUTH)}}"
      - url: "{{env(TEST_2_URL)}}"
        method: "POST"
        headers:
          Content-Type: application/json
          Authorization: "{{env(TEST_2_AUTH)}}"
        body: '{"topic": "/ph/{{%s}}","payload": "{{fake_name}}","retain":true}'
